config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations"  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: "pages#home"
  resources :events do
    collection do
      get :my_events
    end
    member do
      post :attend
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :organizer, class_name: "User"
  has_many :invitations, dependent: :destroy
  has_many :attendees, through: :invitations, source: :attendee

  validates :name, :location, :time, presence: true
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :event

  validates :attendee_id, uniqueness: { scope: :event_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events_organized, class_name: "Event", foreign_key: :organizer_id, dependent: :destroy
  has_many :invitations, foreign_key: :attendee_id, dependent: :destroy
  has_many :events_attended, through: :invitations, source: :event

  validates :name, :email, :password, presence: true
  validates :email, uniqueness: true
end

app/controllers/Users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [ :create ]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

   # GET /resource/edit
   # def edit
   #   super
   # end

   # PUT /resource
   # def update
   #   super
   # end

   # DELETE /resource
   # def destroy
   #   super
   # end

   # GET /resource/cancel
   # Forces the session data which is usually expired after sign
   # in to be expired now. This is useful if the user wants to
   # cancel oauth signing in/up in the middle of the process,
   # removing all OAuth session data.
   # def cancel
   #   super
   # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :name, :email, :password, :password_confirmation ])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  # super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/Users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [ :create ]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [ :attribute ])
  end
end

app/controllers/Users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def my_events
    @events_organized = current_user.events_organized
    @events_attended = current_user.events_attended
  end
  def new
    @event = Event.new
  end

  def create
    @organizer = current_user
    @event = @organizer.events_organized.build(event_params)
    if @event.save
      @event.invitations.create(attendee: @organizer)
      redirect_to events_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def attend
    @event = Event.find(params[:id])
    @invitation = @event.invitations.create(attendee: current_user)

    respond_to do |format|
      format.html { redirect_to event_path(@event), notice: "You are now attending this event." }
      format.turbo_stream # Renders attend.turbo_stream.erb
    end
  end

  private

  def event_params
    params.expect(event: [ :name, :location, :time ])
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/events/attend.turbo_stream.erb
<%= turbo_stream.append "attendees" do %>
  <li><%= current_user == @event.organizer ? "<strong>You</strong>".html_safe : current_user.name %></li>
<% end %>

<%= turbo_stream.remove "attend-link" %>

app/views/events/index.html.erb
<h1>Welcome, <%= current_user.name%></h1>
<h3>Event's list</h3>
<% @events.each do |event|%>
    Event: <%= event.name%><br>
    Organizer: <%= event.organizer.name%><br>
    Location: <%= event.location%><br>
    Time: <%= event.time%><br>
    <%= link_to "See the event", event_path(event)%><br>
<%end%><br>
<%= button_to "Create an event", new_event_path, method: :get%>
<%= button_to "See my events", my_events_events_path, method: :get %>
<br>
<%= link_to 'Sign Out', destroy_user_session_path, data: {turbo_method: :delete} %>

app/views/events/my_events.html.erb
<h3>Your events</h3>
<br>
<h5>Events you organize</h5>
<% if @events_organized.present? %>
<% @events_organized.each do |e|%>
    Name: <%= e.name%><br>
    Location: <%= e.location%><br>
    Time: <%= e.time%><br>
    Attendees: <ul><% e.attendees.each do |attendee|%>
    <li><%= attendee.name %></li>
    <%end%>
    </ul>
    <%= link_to "See the event", event_path(e)%>
<%end%>
<% else %>
  <p>You have no events organized.</p>
<% end %>
<h5>Events you attend</h5>
<% if @events_attended.present? %>
<% @events_attended.each do |e|%>
    Name: <%= e.name%><br>
    Organizer: <%= e.organizer == current_user ? "<strong>You</strong>".html_safe : e.organizer.name%><br>
    Location: <%= e.location%><br>
    Time: <%= e.time%><br>
    Attendees: <ul><% e.attendees.each do |attendee|%>
    <li><%= attendee.name %></li>
    <%end%>
    </ul>
    <%= link_to "See the event", event_path(e)%>
<%end%>
<% else %>
  <p>You are attending no events</p>
<% end %>
<br>
<%= link_to "Go back", :back%>

app/views/events/new.html.erb
<h3>Create new event</h3>
<%= form_with model: @event do |f|%>
    <%= f.label :name, "Event Name:"%>
    <%= f.text_field :name%><br>
    <%= f.label :location, "Event Location:"%>
    <%= f.text_field :location%><br>
    <%= f.label :time, "Event Time:"%>
    <%= f.text_field :time%><br>
    <%= f.submit "Create Event"%>
<%end%>
<%= link_to "Go back", :back%>

app/views/events/show.html.erb
<h3>Event page</h3>

Event: <%= @event.name%><br>
Organizer: <%= @event.organizer.name%><br>
Location: <%= @event.location%><br>
Time: <%= @event.time%><br>
Attendees:
<ul id="attendees">
  <% @event.attendees.each do |attendee| %>
    <li><%= attendee == current_user ? "<strong>You</strong>".html_safe : attendee.name %></li>
  <% end %>
</ul>            
<br>
<% unless @event.attendees.include?(current_user) %>
  <%= link_to "Attend", attend_event_path(@event), method: :post, data: { turbo_method: :post }, class: "btn btn-primary", id: "attend-link" %>
<% end %>
<%= link_to "Go back", :back%>

app/views/invitations/show.html.erb
<h3>Your invitations</h3>

Event: <%= @event.name%>
Organizer: <%= @event.organizer.name%>
Location: <%= @event.location%>
Time: <%= @event.time%>
Attendees: <ul><%= @event.attendees.each do |attendee|%>
<li><%= attendee.name %></li>
</ul>             

<%= link_to "Express interest"%>
<%= link_to "Go back", :back%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Postgresql Test" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to the EverythingApp!</h1>
<% if user_signed_in? %> 
 <div> Hi, <%= current_user.name %>! </div> 
  <%= button_to "See all events", events_path, method: :get %>
  <%= button_to "See my events", my_events_events_path, method: :get %>  
  <%= link_to 'Sign Out', destroy_user_session_path, data: {turbo_method: :delete} %>
<% else %>
<p>Before you go further, you must login!</p>
<%= button_to "Login", new_user_session_path%>
<p>Not a user? Sign-up!</p>
<%= button_to "Sign-up", user_registration_path%>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>